### ISSUE TITLE
Practice: Install Windows Admin Center using a script

### ISSUE THREAD

**Issue by fpreu** [EnterpriseTrainingCenter/WindowsServer#344]
The "Practice: Install Windows Admin Center using a script" is no longer working, because aka.ms/WACDownload now downloads a .exe-file

**Comment by Rokory** [comment]
The issue for the script is here: https://github.com/Easy-On/WS2022/issues/138
Moreover, the slides must be fixed either.

**Comment by Rokory** [comment]
The script will be updated in the next release due January 2025. The slides will be updates at the same time. However, because of lacking documentation from Microsoft, there are several issues with the new release of Windows Admin Center:
- Currently only form login is working with the automated script
- There is no documentation on how to set up WAC in high availability mode. Therefore, the lab regarding the installation of WAC on a cluster will not work completely. However, this does not affect the course.
